CUTADAPT_THREADS="--cores " + Integer.toString(ESSENTIAL_THREADS) // threads to use
CUTADAPT_ADAPTER=ESSENTIAL_TRIMMOMATIC
CUTADAPT_OVERLAP=3 //default=3, could be set to 1 in order to fully clean adapter
CUTADAPT_ERROR_RATE=0.1
CUTADAPT_NEXTSEQTRIM=20
CUTADAPT_EXTRA=" "
CUTADAPT_MINREADLEN=ESSENTIAL_MIN_READLENGTH
